from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class ClientHello:
    """Message sent by a client to initiate a handshake with the server."""

    magic: bytes
    """Protocol-specific constant."""

    nonce: bytes
    """Random bytes generated by the client."""

    public_key: bytes
    """Client public key."""


@dataclass(frozen=True, slots=True)
class ServerHello:
    """Message sent by the server in response to `ClientHello` during handshake."""

    nonce: bytes
    """Random bytes generated by the server."""

    ciphertext: bytes
    """Encrypted key exchange data."""

    handshake_mac: bytes
    """Message authentication code computed over the handshake data."""
